name: CI

on: [push]

jobs:
    build:
        env:
            CI: true

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Install dependencies
              run: npm ci
            - name: Test
              run: npm run test:ci
            - name: Build
              run: npm build
